/**
 * 🏛️ Standard Curated Free Study Hub Seed Data
 * 100% Free Resources: NCERTs, e-Pathshala, IGNOU eGyanKosh, OpenLibrary, YouTube Open Courses
 */

const CURRICULUM_SEED_RESOURCES = [
  // 1. UPSC CSE - Indian Polity
  {
    title: "Historical Background & Making of the Indian Constitution",
    examId: "upsc-cse",
    subject: "Indian Polity & Governance",
    subjectIcon: "🏛️",
    subjectWeightage: "15-18 Questions in Prelims (~30-36 Marks)",
    chapterNo: 1,
    chapterTitle: "Historical Background & Making of the Constitution",
    importance: "🔥 High Yield",
    whatToStudy: "1. Read NCERT Class 11 (Ch 1) -> 2. Laxmikanth (Ch 1 & 2) -> 3. Focus on Regulating Act 1773 to GoI Act 1935.",
    keyConcepts: ["Regulating Act 1773", "GoI Act 1935", "Constituent Assembly", "Objectives Resolution"],
    pyqFocus: "Direct questions on GoI Act 1935 features, Drafting Committee members, and Interim Government portfolios.",
    freeVideoUrl: "https://www.youtube.com/results?search_query=making+of+indian+constitution+upsc+lecture",
    freeVideoChannel: "UPSC Open Masterclasses",
    freeBookName: "NCERT Class 11 Indian Constitution at Work (Official Free PDF)",
    freeBookUrl: "https://ncert.nic.in/textbook.php?keps1=1-10",
    freeBookType: "Official NCERT e-Pathshala",
    officialPortalUrl: "https://upsc.gov.in/examinations/previous-question-papers",
    isPublished: true,
  },
  {
    title: "Preamble, Salient Features & Constitutional Philosophy",
    examId: "upsc-cse",
    subject: "Indian Polity & Governance",
    subjectIcon: "🏛️",
    subjectWeightage: "15-18 Questions in Prelims (~30-36 Marks)",
    chapterNo: 2,
    chapterTitle: "Preamble, Salient Features & Constitutional Philosophy",
    importance: "🔥 High Yield",
    whatToStudy: "1. Laxmikanth Ch 3 & 4 -> 2. Understand Berubari Case (1960), Kesavananda (1973), LIC (1995).",
    keyConcepts: ["Sovereign Socialist Secular Democratic Republic", "42nd Amendment 1976", "Basic Structure Doctrine"],
    pyqFocus: "Exact definitions of 'Republic', 'Liberty of thought', and amendability under Article 368.",
    freeVideoUrl: "https://www.youtube.com/results?search_query=preamble+of+indian+constitution+upsc+lecture",
    freeVideoChannel: "Constitution Open Lectures",
    freeBookName: "NCERT Class 11 - Philosophy of the Constitution",
    freeBookUrl: "https://ncert.nic.in/textbook.php?keps1=10-10",
    freeBookType: "Official NCERT e-Pathshala",
    officialPortalUrl: "https://upsc.gov.in/",
    isPublished: true,
  },
  {
    title: "Fundamental Rights (Articles 12 to 35)",
    examId: "upsc-cse",
    subject: "Indian Polity & Governance",
    subjectIcon: "🏛️",
    subjectWeightage: "15-18 Questions in Prelims (~30-36 Marks)",
    chapterNo: 3,
    chapterTitle: "Fundamental Rights (Articles 12 to 35)",
    importance: "🔥 High Yield (2-3 Qs Every Year)",
    whatToStudy: "1. Read NCERT Class 11 Ch 2 -> 2. Laxmikanth Ch 7 thoroughly -> 3. Memorize all 6 Writs.",
    keyConcepts: ["Articles 14-18 Equality", "Article 21 Privacy & Life", "Article 32 Writs", "Reasonable Restrictions 19(2)"],
    pyqFocus: "Subtle differences between Habeas Corpus vs Mandamus, Reasonable restrictions under Article 19(2).",
    freeVideoUrl: "https://www.youtube.com/results?search_query=fundamental+rights+article+12+to+35+upsc+marathon",
    freeVideoChannel: "Legal & Polity Open Education",
    freeBookName: "NCERT Class 11 - Rights in the Indian Constitution",
    freeBookUrl: "https://ncert.nic.in/textbook.php?keps1=2-10",
    freeBookType: "Official NCERT PDF",
    officialPortalUrl: "https://upsc.gov.in/",
    isPublished: true,
  },
  // 2. UPSC CSE - Modern History
  {
    title: "Revolt of 1857 & Early Resistance Movements",
    examId: "upsc-cse",
    subject: "Modern Indian History",
    subjectIcon: "📜",
    subjectWeightage: "10-12 Questions in Prelims (~20-24 Marks)",
    chapterNo: 1,
    chapterTitle: "Revolt of 1857 & Early Resistance Movements",
    importance: "🔥 High Yield",
    whatToStudy: "1. Spectrum Ch 5 -> 2. NCERT Class 12 Themes in Indian History Part III -> 3. Tabulate leaders per region.",
    keyConcepts: ["Doctrine of Lapse", "General Enlistment Act", "Key Centres & Leaders (Meerut, Delhi, Lucknow, Jhansi)"],
    pyqFocus: "Specific leaders matched with regions (e.g. Kunwar Singh - Bihar, Maulvi Ahmadullah - Faizabad).",
    freeVideoUrl: "https://www.youtube.com/results?search_query=revolt+of+1857+upsc+modern+history+spectrum",
    freeVideoChannel: "History Open Series",
    freeBookName: "NCERT Class 12 Themes in Indian History III (Free PDF)",
    freeBookUrl: "https://ncert.nic.in/textbook.php?lehs3=1-6",
    freeBookType: "Official NCERT Textbook",
    officialPortalUrl: "https://upsc.gov.in/",
    isPublished: true,
  },
  // 3. SSC CGL - Quantitative Aptitude
  {
    title: "Percentage, Profit, Loss & Discount Formulas",
    examId: "ssc-cgl",
    subject: "Quantitative Aptitude (Maths)",
    subjectIcon: "📐",
    subjectWeightage: "Tier 1: 25 Qs (50 Marks) | Tier 2: 30 Qs (90 Marks)",
    chapterNo: 1,
    chapterTitle: "Percentage, Profit, Loss & Discount Formulas",
    importance: "🔥 Core Foundation (3-4 Qs)",
    whatToStudy: "1. Memorize fraction-to-percentage conversion chart (1/1 to 1/20) -> 2. Successive percentage change.",
    keyConcepts: ["Fraction to Percentage Equivalents", "Successive Change Formula", "Marked Price & True Discount", "Dishonest Shopkeeper Tricks"],
    pyqFocus: "Dishonest shopkeeper selling by false weight; Successive discounts combined with GST calculations.",
    freeVideoUrl: "https://www.youtube.com/results?search_query=percentage+and+profit+loss+ssc+cgl+complete+marathon",
    freeVideoChannel: "SSC Maths Masterclass",
    freeBookName: "Open Quantitative Aptitude Practice Sheet (Free PDF)",
    freeBookUrl: "https://archive.org/details/quantitativeapti0000agar",
    freeBookType: "OpenLibrary & Archive",
    officialPortalUrl: "https://ssc.gov.in/",
    isPublished: true,
  },
  {
    title: "Time, Speed, Distance, Trains & Boats & Streams",
    examId: "ssc-cgl",
    subject: "Quantitative Aptitude (Maths)",
    subjectIcon: "📐",
    subjectWeightage: "Tier 1: 25 Qs (50 Marks) | Tier 2: 30 Qs (90 Marks)",
    chapterNo: 2,
    chapterTitle: "Time, Speed, Distance, Trains & Boats & Streams",
    importance: "🔥 High Yield (2-3 Qs)",
    whatToStudy: "1. km/h to m/s conversions (* 5/18) -> 2. Relative speed (Same vs Opposite direction) -> 3. Circular track meetings.",
    keyConcepts: ["Relative Speed in Same vs Opposite Direction", "Train crossing bridge vs pole", "Upstream vs Downstream Boat Speeds"],
    pyqFocus: "Two trains starting simultaneously from A and B and meeting after t hours formula.",
    freeVideoUrl: "https://www.youtube.com/results?search_query=time+speed+distance+trains+boats+streams+ssc+cgl",
    freeVideoChannel: "SSC Open Aptitude Hub",
    freeBookName: "NCERT Class 10 Mathematics - Real World Applications",
    freeBookUrl: "https://ncert.nic.in/textbook.php?jemh1=0-15",
    freeBookType: "Official NCERT PDF",
    officialPortalUrl: "https://ssc.gov.in/",
    isPublished: true,
  },
  // 4. SSC CGL - General Awareness
  {
    title: "Static GK: Classical Dances, Festivals & National Parks",
    examId: "ssc-cgl",
    subject: "General Awareness (GK & Science)",
    subjectIcon: "🌍",
    subjectWeightage: "Tier 1: 25 Qs (50 Marks) | Tier 2: 25 Qs (75 Marks)",
    chapterNo: 1,
    chapterTitle: "Static GK: Classical Dances, Festivals & National Parks",
    importance: "🔥 4-5 Questions Guaranteed",
    whatToStudy: "1. 8 Classical Dances & associated Padma awardees -> 2. State-wise tribal festivals -> 3. Biosphere reserves & UNESCO heritage sites.",
    keyConcepts: ["8 Sangeet Natak Akademi Classical Dances", "State Harvest Festivals", "UNESCO World Heritage Sites in India", "Tiger Reserves Map"],
    pyqFocus: "Matching exponents with dance forms (e.g. Birju Maharaj, Rukmini Devi, Kelucharan Mohapatra).",
    freeVideoUrl: "https://www.youtube.com/results?search_query=static+gk+classical+dances+festivals+national+parks+ssc+cgl",
    freeVideoChannel: "Static GK Open Hub",
    freeBookName: "CCRT India Official Art & Heritage Compendium",
    freeBookUrl: "http://ccrtindia.gov.in/",
    freeBookType: "Official Cultural Portal",
    officialPortalUrl: "https://ssc.gov.in/",
    isPublished: true,
  },
  // 5. State PSC / APPSC / TSPSC
  {
    title: "Indian Economy, Planning & NITI Aayog",
    examId: "state-psc",
    subject: "Economy & Development",
    subjectIcon: "📈",
    subjectWeightage: "Group 1 & 2 Core Paper (50 Marks)",
    chapterNo: 1,
    chapterTitle: "Indian Economy, Planning & NITI Aayog",
    importance: "🔥 High Yield",
    whatToStudy: "1. Five Year Plans 1st to 12th -> 2. NITI Aayog structure & SDG India Index -> 3. Inflation indices (CPI vs WPI).",
    keyConcepts: ["Harrod-Domar & Mahalanobis Models", "NITI Aayog Governing Council", "Monetary Policy Committee (MPC)", "Budget Terminology (Fiscal vs Revenue Deficit)"],
    pyqFocus: "Targets vs Achievements in 11th and 12th FYP; Composition and reports of NITI Aayog.",
    freeVideoUrl: "https://www.youtube.com/results?search_query=indian+economy+planning+niti+aayog+group+2+group+1",
    freeVideoChannel: "State PSC Master Lectures",
    freeBookName: "NCERT Class 11 Indian Economic Development (Free PDF)",
    freeBookUrl: "https://ncert.nic.in/textbook.php?keec1=1-10",
    freeBookType: "Official NCERT e-Pathshala",
    officialPortalUrl: "https://psc.ap.gov.in/",
    isPublished: true,
  },
  // 6. Engineering / Computer Science
  {
    title: "Data Structures: Trees, Graphs & Dynamic Programming",
    examId: "engineering-cs",
    subject: "Computer Science & Engineering",
    subjectIcon: "💻",
    subjectWeightage: "GATE & Placement Core (20-25 Marks)",
    chapterNo: 1,
    chapterTitle: "Data Structures: Trees, Graphs & Dynamic Programming",
    importance: "🔥 High Yield",
    whatToStudy: "1. BST, AVL & Red-Black Tree operations -> 2. Graph traversals (BFS, DFS, Dijkstra, Bellman-Ford) -> 3. Standard DP problems (0/1 Knapsack, LCS, LIS).",
    keyConcepts: ["Binary Search Tree Properties", "Dijkstra Shortest Path", "0/1 Knapsack DP", "Time & Space Asymptotics"],
    pyqFocus: "Constructing BST from traversals; Finding minimum spanning tree weight using Kruskal/Prim.",
    freeVideoUrl: "https://www.youtube.com/results?search_query=data+structures+algorithms+gate+computer+science+nptel",
    freeVideoChannel: "NPTEL & Open Courseware",
    freeBookName: "OpenDSA Interactive Data Structures & Algorithms",
    freeBookUrl: "https://opendsa-server.cs.vt.edu/",
    freeBookType: "Open-source Textbook",
    officialPortalUrl: "https://nptel.ac.in/",
    isPublished: true,
  },
];

module.exports = { CURRICULUM_SEED_RESOURCES };
